version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    branches:
      only:
        - solution
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven
      - run: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
